[build]
  # Tell Netlify to enter the client folder first
  base = "client"
  # This command is run INSIDE the client folder
  command = "npm run build"
  # Next.js builds into this folder
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"